CREATE TABLE [dbo].[FAVOURITES](
	[userID] [int] NOT NULL,
	[interested_in] [nvarchar](50) NOT NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FAVOURITES]  WITH CHECK ADD  CONSTRAINT [FK_FAVOURITES_USER] FOREIGN KEY([userID])
REFERENCES [dbo].[USER] ([userID])
GO

ALTER TABLE [dbo].[FAVOURITES] CHECK CONSTRAINT [FK_FAVOURITES_USER]
GO

