CREATE TABLE [dbo].[FRIENDS](
	[userID] [int] NOT NULL,
	[friendID] [int] NOT NULL,
 CONSTRAINT [PK_FRIENDS] PRIMARY KEY CLUSTERED 
(
	[friendID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO