USE [mdiola01]
GO

ALTER TABLE [dbo].[COMMENTS] DROP CONSTRAINT [FK_COMMENTS_VIDEO]
GO

ALTER TABLE [dbo].[COMMENTS] DROP CONSTRAINT [FK_COMMENTS_USER]
GO

ALTER TABLE [dbo].[COMMENTS] DROP CONSTRAINT [FK_COMMENTS_ALBUM]
GO

/****** Object:  Table [dbo].[COMMENTS]    Script Date: 04/12/2020 11:17:15 pm ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[COMMENTS]') AND type in (N'U'))
DROP TABLE [dbo].[COMMENTS]
GO

/****** Object:  Table [dbo].[COMMENTS]    Script Date: 04/12/2020 11:17:15 pm ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COMMENTS](
	[commentsID] [int] NOT NULL,
	[userID] [int] NOT NULL,
	[comments] [nvarchar](200) NOT NULL,
	[albumID] [int] NULL,
	[videoID] [int] NULL,
 CONSTRAINT [PK_COMMENTS] PRIMARY KEY CLUSTERED 
(
	[commentsID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[COMMENTS]  WITH CHECK ADD  CONSTRAINT [FK_COMMENTS_ALBUM] FOREIGN KEY([albumID])
REFERENCES [dbo].[ALBUM] ([albumID])
GO

ALTER TABLE [dbo].[COMMENTS] CHECK CONSTRAINT [FK_COMMENTS_ALBUM]
GO

ALTER TABLE [dbo].[COMMENTS]  WITH CHECK ADD  CONSTRAINT [FK_COMMENTS_USER] FOREIGN KEY([userID])
REFERENCES [dbo].[USER] ([userID])
GO

ALTER TABLE [dbo].[COMMENTS] CHECK CONSTRAINT [FK_COMMENTS_USER]
GO

ALTER TABLE [dbo].[COMMENTS]  WITH CHECK ADD  CONSTRAINT [FK_COMMENTS_VIDEO] FOREIGN KEY([videoID])
REFERENCES [dbo].[VIDEO] ([videoID])
GO

ALTER TABLE [dbo].[COMMENTS] CHECK CONSTRAINT [FK_COMMENTS_VIDEO]
GO


