USE [mdiola01]
GO

ALTER TABLE [dbo].[FRIENDS] DROP CONSTRAINT [FK_FRIENDS_USER]
GO

/****** Object:  Table [dbo].[FRIENDS]    Script Date: 04/12/2020 11:18:35 pm ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[FRIENDS]') AND type in (N'U'))
DROP TABLE [dbo].[FRIENDS]
GO

/****** Object:  Table [dbo].[FRIENDS]    Script Date: 04/12/2020 11:18:35 pm ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FRIENDS](
	[userID] [int] NOT NULL,
	[friendID] [int] NOT NULL,
 CONSTRAINT [PK_FRIENDS] PRIMARY KEY CLUSTERED 
(
	[friendID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FRIENDS]  WITH CHECK ADD  CONSTRAINT [FK_FRIENDS_USER] FOREIGN KEY([userID])
REFERENCES [dbo].[USER] ([userID])
GO

ALTER TABLE [dbo].[FRIENDS] CHECK CONSTRAINT [FK_FRIENDS_USER]
GO


